### ISSUE TITLE
X11 forwarding request failed on channel 0

### ISSUE THREAD

**Issue by LaurensRietveld** [DesktopContainers/icaclient#6]
First, thanks for this docker img. Enjoying using citrix without having to mess around with dependencies (this might be the first time that 'enjoying' and 'citrix' are used in the same sentence).

Since recently I can't connect via ssh though. When ssh-ing, I'm getting the error `X11 forwarding request failed on channel 0`. Firefox does start, but closes with msg `no display specified`.
Not sure what the root cause is. Perhaps a version upgrade of some deps in the dockerfile?
Anyway, the fix I'm using is running this before ssh-ing:
`docker exec -it $(docker-compose ps -q) /bin/bash -c 'echo "X11UseLocalhost no" >> /etc/ssh/sshd_config && sudo service ssh restart'`

**Comment by MarvAmBass** [comment]
Hi Laurens,

thanks for using my Image, and also thanks for this bug request, I'll look into it

Kind regards

Marvin

**Comment by MarvAmBass** [comment]
thanks seems like a debian update broke my containers, I fixed this on my base container.

hope in a few hours all my containers are running again.

Thank you

Marvin

**Comment by MarvAmBass** [comment]
so it's working again
